### ISSUE TITLE
도커 컴포즈 설정

### ISSUE THREAD

**Issue by gdtknight** [gdtknight/my-blog#3]
- [x] `compose.yml` 작성

```yaml
version: '3'

services:
  mysql:
    container_name: pre_onboarding_mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${BASIC_BOARD_USER}
      MYSQL_PASSWORD: ${BASIC_BOARD_PASSWORD}
      MYSQL_DATABASE: ${BASIC_BOARD_DATABASE}
    ports:
      - ${BASIC_BOARD_PORTS}
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
```

- [x] `.env` 파일 생성 - `Local` 에서 별도로 관리 예정
